/*CAU1A*/
SELECT IIF(LUONG >= LTB,'KHONG TANG LUONG','TANG LUONG') AS THUONG,TENNV,LUONG,LTB 
FROM 
(SELECT TENNV,LUONG,LTB FROM NHANVIEN,
(SELECT PHG,AVG(LUONG) AS 'LTB' 
FROM NHANVIEN GROUP BY PHG) AS TEMP 
WHERE NHANVIEN.PHG =TEMP.PHG) AS ABC
GO
/*CAU1B*/
SELECT IIF(LUONG <= LTB,'NHAN VIEN','TRUONG PHONG') AS CHUCVU,TENNV,LUONG,LTB 
FROM 
(SELECT TENNV,LUONG,LTB FROM NHANVIEN,
(SELECT PHG,AVG(LUONG) AS 'LTB' FROM NHANVIEN 
GROUP BY PHG) AS TEMP 
WHERE NHANVIEN.PHG =TEMP.PHG) AS ABC
GO
/*CAU1C*/
SELECT TENNV = CASE PHAI
	WHEN 'Nam' THEN 'Mr. ' + [TENNV]
	ELSE 'Mrs. ' + [TENNV]
	END
FROM NHANVIEN
GO
/*CAU1D*/
SELECT TENNV, LUONG, THUE = CASE
	WHEN LUONG BETWEEN 0 AND 25000 THEN LUONG*0.1
	WHEN LUONG BETWEEN 25000 AND 30000 THEN LUONG*0.12
	WHEN LUONG BETWEEN 30000 AND 40000 THEN LUONG*0.15
	WHEN LUONG BETWEEN 40000 AND 50000 THEN LUONG*0.2
	ELSE LUONG*0.25
	END
FROM NHANVIEN
GO
/*CAU2A*/
SELECT HONV, TENLOT, TENNV, MANV
FROM NHANVIEN
WHERE MANV%2=0
GO
/*CAU2B*/
SELECT HONV, TENLOT, TENNV, MANV
FROM NHANVIEN
WHERE MANV%2=0 AND MANV!=4
GO
/*CAU3A*/
BEGIN TRY
DECLARE @result INT

SET @result = 55/0
END TRY
BEGIN CATCH
DECLARE
@ErMessage NVARCHAR(2048),
@ErSeverity INT,
@ErState INT
SELECT
@ErMessage = ERROR_MESSAGE(), 
@ErSeverity = ERROR_SEVERITY(),
@ErState = ERROR_STATE()
RAISERROR(
@ErMessage,
@ErSeverity,
@ErState
)
END CATCH
GO
/*CAU3B*/
DECLARE @TONG INT = 0
DECLARE @I INT = 0
WHILE @I<=10
BEGIN
	IF(@I%2=0)
	BEGIN
		SET @TONG = @TONG + @I
		
	END
	SET @I = @I + 1
END
PRINT 'Tong cac so chan tu (1->10) = ' + convert(varchar, @TONG)
GO
DECLARE @TONG INT = 0
DECLARE @I INT = 0
WHILE @I<=10
BEGIN
IF(@I!=4)
	IF(@I%2=0)
	BEGIN
		SET @TONG = @TONG + @I
		
	END
	SET @I = @I + 1
END
PRINT 'Tong cac so chan tu (1->10) = ' + convert(varchar, @TONG)