--BÀI 1A
CREATE PROC B1A @NAME NVARCHAR(20)
AS
BEGIN
PRINT 'XIN CHÀO: ' + @NAME
END
EXEC B1A 'THIÊN TÍNH'
GO
--BÀI 1B
CREATE PROC B1B @SO1 INT, @SO2 INT
AS
BEGIN
DECLARE @TONG INT = 0;
SET @TONG = @SO1 + @SO2 
PRINT 'TỔNG: ' + CAST(@TONG AS VARCHAR(10))
END
EXEC B1B 7,8
GO
--BÀI 1C
CREATE PROC B1C @L INT
AS
BEGIN
DECLARE @TONG INT = 0, @I INT = 0;
WHILE @I < @L
BEGIN
SET @TONG = @TONG + @I
SET @I = @I + 2
END
PRINT 'TỔNG: ' + CAST(@TONG AS VARCHAR(10))
END
EXEC B1C 15
GO
--BÀI 1D
CREATE PROC B1D @A INT, @B INT
AS
BEGIN
WHILE (@A != @B)
BEGIN
IF(@A > @B)
SET @A = @A -@B
ELSE
SET @B = @B - @A
END
RETURN @A
END
DECLARE @L INT
EXEC @L = B1D 5,7
PRINT @L
GO
--BÀI 2A
CREATE PROC B2A @MANV VARCHAR(20)
AS
BEGIN
SELECT * FROM NHANVIEN WHERE MANV = @MANV
END
EXEC B2A '003'
GO
--BÀI 2B
SELECT COUNT(MANV), MADA, TENPHG FROM NHANVIEN
INNER JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
INNER JOIN DEAN ON DEAN.PHONG = PHONGBAN.MAPHG
WHERE MADA = 2
GROUP BY TENPHG,MADA
GO
CREATE PROC B2B @MANV INT
AS
BEGIN
SELECT COUNT(MANV) AS 'SỐ LƯỢNG', MADA, TENPHG FROM NHANVIEN
INNER JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
INNER JOIN DEAN ON DEAN.PHONG = PHONGBAN.MAPHG
WHERE MADA = @MANV
GROUP BY TENPHG,MADA
END
EXEC B2B 10
GO
--BÀI 2C
SELECT COUNT(MANV)AS 'SỐ LƯƠNG', MADA, TENPHG FROM NHANVIEN
INNER JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
INNER JOIN DEAN ON DEAN.PHONG = PHONGBAN.MAPHG
WHERE MADA = 2 AND DDIEM_DA = 'NHA TRANG'
GROUP BY TENPHG,MADA
GO
--BÀI 2D
SELECT HONV, TENNV, TENPHG, NHANVIEN.MANV, THANNHAN.*
FROM NHANVIEN
INNER JOIN PHONGBAN ON PHONGBAN.MAPHG = NHANVIEN.PHG
LEFT OUTER JOIN THANNHAN ON THANNHAN.MA_NVIEN = NHANVIEN.MANV
WHERE THANNHAN.MA_NVIEN IS NULL AND TRPHG = '008'
GO
CREATE PROC B2D @MATP VARCHAR(10)
AS
BEGIN
SELECT HONV, TENNV, TENPHG, NHANVIEN.MANV, THANNHAN.*
FROM NHANVIEN
INNER JOIN PHONGBAN ON PHONGBAN.MAPHG = NHANVIEN.PHG
LEFT OUTER JOIN THANNHAN ON THANNHAN.MA_NVIEN = NHANVIEN.MANV
WHERE THANNHAN.MA_NVIEN IS NULL AND TRPHG = @MATP
END
EXEC B2D '008'
GO
--BÀI 2E
IF EXISTS (SELECT * FROM NHANVIEN WHERE MANV = '001' AND PHG = '5')
PRINT 'NHÂN VIÊN CÓ TRONG PHÒNG BAN'
ELSE 
PRINT 'NHÂN VIÊN KHÔNG CÓ TRONG PHÒNG BAN'
GO
CREATE PROC B2E @MANV VARCHAR(10), @MAPB VARCHAR(10)
AS
BEGIN
IF EXISTS(SELECT * FROM NHANVIEN WHERE MANV = '001' AND PHG=@MAPB)
PRINT 'NHÂN VIÊN:' + @MANV +'CÓ TRONG PHÒNG BAN: '+@MAPB
ELSE 
PRINT 'NHÂN VIÊN: '+ @MANV+'KHÔNG CÓ TRONG PHÒNG BAN: '+@MAPB
END
EXEC B2E '001 ','5'
GO
--BÀI 3A
INSERT INTO PHONGBAN(MAPHG, TENPHG, TRPHG, NG_NHANCHUC)
VALUES ('7','CNTT','008','2002-07-28')
GO
CREATE PROC B3A
@MAPB INT, @TENPB NVARCHAR(20),
@MATP VARCHAR(10), @NGAYNHANCHUC DATE
AS
BEGIN
IF(EXISTS(SELECT * FROM PHONGBAN WHERE MAPHG=@MAPB))
PRINT'THÊM THẤT BẠI'
ELSE 
BEGIN
INSERT INTO PHONGBAN(MAPHG, TENPHG, TRPHG, NG_NHANCHUC)
VALUES (@MAPB,@TENPB,@MATP,@NGAYNHANCHUC)
PRINT 'THÊM THÀNH CÔNG'
END
END
EXEC B3A '7','CNTT','008','2002-07-28'
GO
--BÀI 3B
CREATE PROC B3B
@MAPB INT, @TENPB NVARCHAR(20),
@MATP VARCHAR(10), @NGAYNHANCHUC DATE
AS
BEGIN
IF(EXISTS(SELECT * FROM PHONGBAN WHERE MAPHG=@MAPB))
UPDATE PHONGBAN SET TENPHG =@TENPB, TRPHG=@MATP,NG_NHANCHUC =@NGAYNHANCHUC
WHERE MAPHG = @MAPB
ELSE 
BEGIN
INSERT INTO PHONGBAN(MAPHG, TENPHG, TRPHG, NG_NHANCHUC)
VALUES (@MAPB,@TENPB,@MATP,@NGAYNHANCHUC)
PRINT 'THÊM THÀNH CÔNG'
END
END
EXEC B3B '7','CNTT','008','2002-07-28'
--BÀI 3C
SELECT HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG FROM NHANVIEN
INSERT INTO NHANVIEN(HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
VALUES('NGUYỄN', 'THIÊN', 'TÍNH', '129', '2001-09-30', 'TP.HCM', 'NAM','25000', '004', '6')
GO
CREATE PROC B3C
@HONV VARCHAR(10), @TENLOT VARCHAR(10), @TENNV VARCHAR(10),
@MANV VARCHAR(10), @NGSINH DATE, @DCHI VARCHAR(50), @PHAI VARCHAR(10),
@LUONG FLOAT, @MA_NQL VARCHAR(10) = NULL, @PHG INT
AS
BEGIN
DECLARE @AGE INT
SET @AGE = YEAR(GETDATE()) - YEAR(@NGSINH)
IF @PHG = (SELECT MAPHG FROM PHONGBAN WHERE TENPHG ='CNTT')
BEGIN
IF @LUONG < 25000
SET @MA_NQL = '009'
ELSE SET @MA_NQL= '005'
IF(@PHAI = 'NAM' AND (@AGE >= 18 AND @AGE >= 65))
OR (@PHAI = N'NỮ' AND (@AGE >= 18 AND @AGE >= 60))
BEGIN
INSERT INTO NHANVIEN(HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
VALUES(@HONV, @TENLOT, @TENNV, @MANV, @NGSINH, @DCHI, @PHAI, @LUONG, @MA_NQL, @PHG)
END
ELSE
PRINT 'KHÔNG THUỘC ĐỘ TUỔI LAO ĐỘNG'
END
ELSE
PRINT 'KHÔNG PHẢI PHÒNG CNTT'
END
EXEC B3C 'LÊ', 'HOÀI', 'LINH', '129', '2002-07-28', 'TÂY NINH', 'NAM','25000', '004', '6'
EXEC B3C 'NGUYỄN', 'THIÊN', 'TÍNH', '130', '2020-09-5', 'TP HCM', 'NAM','25000', '005', '9'
EXEC B3C 'ĐẶNG', 'VĂN', 'TIÊN', '018', '1954-02-11', 'BÌNH ĐỊNH', 'NAM','25000', '004', '6'
