--CÂU 1A
CREATE TRIGGER  TRG_CHECKSALARY15000
ON NHANVIEN
FOR INSERT, UPDATE
AS
IF (SELECT LUONG FROM INSERTED)<15000
BEGIN
PRINT N'LƯƠNG > 15000';
ROLLBACK TRAN;
END
SELECT * FROM NHANVIEN
INSERT INTO [DBO].[NHANVIEN] ([HONV],[TENLOT],[TENNV],[MANV],[NGSINH],[DCHI],[PHAI],[LUONG],[MA_NQL],[PHG])
VALUES(N'NGUYEN',N'THIEN',N'TINH','098','09-30-2020','NGUYEN KIEM - TPHCM','NAM',6000,'005',1)
GO
--CÂU 1B
CREATE TRIGGER TRG_CHECKVALIDAGE
ON NHANVIEN
FOR INSERT
AS
DECLARE @AGE INT;
SELECT @AGE = DATEDIFF(YEAR, NGSINH, GETDATE())+1 FROM INSERTED;
IF @AGE <18 OR @AGE >65
BEGIN
PRINT N'TUỔI CỦA NHÂN VIÊN KHÔNG HỢP LỆ 18<= TUỔI <= 65';
ROLLBACK TRANSACTION;
END
INSERT INTO [DBO].[NHANVIEN] ([HONV],[TENLOT],[TENNV] ,[MANV] ,[NGSINH],[DCHI],[PHAI],[LUONG],[MA_NQL],[PHG])
VALUES(N'NGUYEN',N'THIEN',N'TINH','098','09-30-2020','NGUYEN KIEM - TPHCM','NAM',90000,'005',1)
GO
---CÂU 1C
CREATE TRIGGER TRG_CHECKUPDATEONADDRESS
ON NHANVIEN
FOR UPDATE
AS
IF EXISTS (SELECT DCHI FROM INSERTED WHERE DCHI LIKE '%HCM%')
BEGIN
PRINT N'KHÔNG THỂ CẬP NHẬT NHÂN VIÊN Ở TPHCM';
ROLLBACK TRAN;
END;
UPDATE [DBO].[NHANVIEN]
SET [PHAI] = 'NAM'
WHERE MANV = '001';
GO
----BÀI 2A
CREATE TRIGGER TRG_SUMEMPS
ON NHANVIEN
AFTER INSERT
AS
DECLARE @MALE INT, @FEMALE INT;
SELECT @FEMALE = COUNT(MANV) FROM NHANVIEN WHERE PHAI = N'NỮ';
SELECT @MALE = COUNT(MANV) FROM NHANVIEN WHERE PHAI = N'NAM';
PRINT N'TỔNG SỐ NHÂN VIÊN LÀ NỮ: ' + CAST(@FEMALE AS VARCHAR);
PRINT N'TỔNG SỐ NHÂN VIÊN LÀ NAM: ' + CAST(@MALE AS VARCHAR);
INSERT INTO [DBO].[NHANVIEN]([HONV],[TENLOT],[TENNV],[MANV],[NGSINH],[DCHI],[PHAI],[LUONG],[MA_NQL],[PHG])
VALUES ('NGUYEN','THIEN','TINH','345','9-30-2001','TPHCM','NAM',600000,'005',1)
GO
 --BÀI 2B
CREATE TRIGGER TRG_SUMEMPSFORUPDATE
ON NHANVIEN
AFTER UPDATE
AS
IF (SELECT TOP 1 PHAI FROM DELETED) != (SELECT TOP 1 PHAI FROM INSERTED)
BEGIN
DECLARE @MALE INT, @FEMALE INT;
SELECT @FEMALE = COUNT(MANV) FROM NHANVIEN WHERE PHAI = N'NỮ';
SELECT @MALE = COUNT(MANV) FROM NHANVIEN WHERE PHAI = N'NAM';
PRINT N'TỔNG SỐ NHÂN VIÊN LÀ NỮ: ' + CAST(@FEMALE AS VARCHAR);
PRINT N'TỔNG SỐ NHÂN VIÊN LÀ NAM: ' + CAST(@MALE AS VARCHAR);
   END;
UPDATE [DBO].[NHANVIEN]
   SET [HONV] = 'TÍNH'
      ,[PHAI] = N'NAM'
 WHERE  MANV = '345'
GO
---BÀI 2C
CREATE TRIGGER TRG_SUMFORDELETE
ON DEAN
AFTER DELETE
AS
SELECT MA_NVIEN, COUNT(MADA) AS 'TỔNG SỐ ĐỀ ÁN ĐÃ THAM GIA' FROM PHANCONG
GROUP BY MA_NVIEN
GO
--BÀI 3A
CREATE TRIGGER TRG_DELETENHANTHANNV ON NHANVIEN
INSTEAD OF DELETE 
AS
BEGIN
DELETE FROM THANNHAN WHERE MA_NVIEN IN (SELECT MANV FROM DELETED)
DELETE FROM NHANVIEN WHERE MANV IN (SELECT MANV FROM DELETED)
END
DELETE NHANVIEN WHERE MANV='001'
SELECT * FROM THANNHAN
GO
--BÀI 3B
CREATE TRIGGER TRG_NHANVIEN3B ON NHANVIEN
AFTER INSERT
AS 
BEGIN 
INSERT INTO PHANCONG VALUES((SELECT MANV FROM INSERTED),1,1,100)
END
INSERT INTO NHANVIEN
VALUES('NGUYEN','THIEN','TINH','098','09-13-2020','NGUYEN KIEM - TPHCM','NAM',90000,'005',1)