--1
CREATE FUNCTION DIEMTB (@MSV CHAR(5))
RETURNS FLOAT
AS
BEGIN
DECLARE @TB FLOAT
SET @TB = (SELECT AVG(DIEMTHI)
FROM KETQUA
WHERE MASV=@MSV)
RETURN @TB
END
GO
SELECT DBO.DIEMTB ('01')GO
--2
--C 1
CREATE FUNCTION TRBINHLOP(@MALOP CHAR(5))
RETURNS TABLE
AS
RETURN
SELECT S.MASV, HOTEN, TRUNGBINH=DBO.DIEMTB(S.MASV)
FROM SINHVIEN S JOIN KETQUA K ON S.MASV=K.MASV
WHERE MALOP=@MALOP
GROUP BY S.MASV, HOTEN
--C 2
GO
CREATE FUNCTION TRBINHLOP1(@MALOP CHAR(5))
RETURNS @DSDIEMTB TABLE (MASV CHAR(5), TENSV NVARCHAR(20), DTB FLOAT)
AS
BEGIN
INSERT @DSDIEMTB
SELECT S.MASV, HOTEN, TRUNGBINH=DBO.DIEMTB(S.MASV)
FROM SINHVIEN S JOIN KETQUA K ON S.MASV=K.MASV
WHERE MALOP=@MALOP
GROUP BY S.MASV, HOTEN
RETURN
END
GO
SELECT*FROM TRBINHLOP1('A')--3
GO
CREATE PROC KTRA @MSV CHAR(5)
AS
BEGIN
DECLARE @N INT
SET @N=(SELECT COUNT(*) FROM KETQUA WHERE MASV=@MSV)
IF @N=0
PRINT 'SINH VIEN '+@MSV + 'KHONG THI MON NAO'
ELSE
PRINT 'SINH VIEN '+ @MSV+ 'THI '+CAST(@N AS CHAR(2))+ 'MON'
END
GO
EXEC KTRA '01'
--4
GO
CREATE TRIGGER UPDATESSLOP
ON SINHVIEN
FOR INSERT
AS
BEGIN
DECLARE @SS INT
SET @SS=(SELECT COUNT(*) FROM SINHVIEN S
WHERE MALOP IN(SELECT MALOP FROM INSERTED))
IF @SS>10
BEGIN
PRINT 'LOP DAY'
ROLLBACK TRAN
END
ELSE
BEGIN
UPDATE LOP
SET SISO=@SS
WHERE MALOP IN (SELECT MALOP FROM INSERTED)
END
